package globals

const GATEWAY_SOAP_REQUEST string = "GATEWAY_SOAP_REQUEST"
const GATEWAY_REQUEST_TIMEOUT string = "GATEWAY_REQUEST_TIMEOUT"
const PAYMENT_CALLBACK_REQUEST string = "PAYMENT_CALLBACK_REQUEST"
const GATEWAY_PAYMENT_REQUEST string = "GATEWAY_PAYMENT_REQUEST"
const GATEWAY_CHECKSUM_VERIFY_FAILED string = "GATEWAY_CHECKSUM_VERIFY_FAILED"
const GATEWAY_ERROR_DATA_MISMATCH string = "GATEWAY_ERROR_DATA_MISMATCH"
const GATEWAY_ERROR_TIMED_OUT string = "GATEWAY_ERROR_TIMED_OUT"
const GATEWAY_ERROR_USER_INACTIVE string = "GATEWAY_ERROR_USER_INACTIVE"
